import { createFileRoute } from "@tanstack/react-router";
import { Section } from "@/components/site/Section";
import { BUSINESS, DISCLAIMERS, absUrl } from "@/lib/business-config";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — KhanaBook" },
      { name: "description", content: `Privacy Policy for KhanaBook, a product of ${BUSINESS.legalName}.` },
      { property: "og:url", content: absUrl("/privacy-policy") },
    ],
    links: [{ rel: "canonical", href: absUrl("/privacy-policy") }],
  }),
  component: PrivacyPolicy,
});


function PrivacyPolicy() {
  return (
    <Section eyebrow="Legal" title={<>Privacy <span className="hl">Policy.</span></>}>
      <div className="max-w-3xl mx-auto space-y-6 text-muted-foreground leading-relaxed">
        <p>
          This Privacy Policy describes how <strong className="text-foreground">{BUSINESS.legalName}</strong> ("we", "us") handles personal information in relation to the KhanaBook restaurant POS product.
        </p>
        <p><em>Effective date: {BUSINESS.effectiveDate}. Last updated: {BUSINESS.lastUpdatedDate}.</em></p>

        <Block title="Data we collect">
          Restaurant and user information (business name, contact details, staff logins), device and diagnostic information, and billing and transaction records generated by using KhanaBook.
        </Block>
        <Block title="Local device storage">
          Bills, menus and related records are stored on the device to allow offline operation.
        </Block>
        <Block title="Cloud synchronisation">
          When connectivity is available, records are synchronised to our cloud infrastructure for backup and restaurant-level reporting.
        </Block>
        <Block title="Third-party processors and payment partners">
          We may share limited information with third-party processors and payment partners strictly to provide the service you have requested.
        </Block>
        <Block title="Retention">
          We retain information for as long as the account is active and for a reasonable period thereafter, or as required by law.
        </Block>
        <Block title="Security">
          {DISCLAIMERS.security}
        </Block>
        <Block title="Your rights">
          You may request access, correction, export or deletion of your data by contacting us.
        </Block>
        <Block title="Grievance contact">
          Grievance Officer: {BUSINESS.grievanceOfficer}. Email: {BUSINESS.supportEmail}. Address: {BUSINESS.registeredAddress}.
        </Block>
      </div>
    </Section>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-lg font-black text-foreground mb-2">{title}</h2>
      <p>{children}</p>
    </div>
  );
}
